version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://localhost:8000"
        REACT_APP_API_KEY: "Sabrina_afrin_489398095647"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
